# Generated by Django 4.2.9 on 2024-02-12 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'option',
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'permissions',
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='permissionOptionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.option')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.permission')),
            ],
            options={
                'verbose_name': 'permissionOptionRole',
                'db_table': 'permission_option_role',
            },
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('roleToOptions', models.ManyToManyField(through='modelos.permissionOptionRole', to='modelos.option')),
                ('roleTopermissions', models.ManyToManyField(through='modelos.permissionOptionRole', to='modelos.permission')),
            ],
            options={
                'verbose_name': 'role',
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='permissionoptionrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.role'),
        ),
        migrations.AddField(
            model_name='permission',
            name='permissionToOptions',
            field=models.ManyToManyField(through='modelos.permissionOptionRole', to='modelos.option'),
        ),
        migrations.AddField(
            model_name='permission',
            name='permissionToRoles',
            field=models.ManyToManyField(through='modelos.permissionOptionRole', to='modelos.role'),
        ),
        migrations.AddField(
            model_name='option',
            name='optionToPermissions',
            field=models.ManyToManyField(through='modelos.permissionOptionRole', to='modelos.permission'),
        ),
        migrations.AddField(
            model_name='option',
            name='optionToRoles',
            field=models.ManyToManyField(through='modelos.permissionOptionRole', to='modelos.role'),
        ),
    ]
