# Generated by Django 4.2.9 on 2024-02-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltest',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
