# Generated by Django 4.2.9 on 2024-03-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_modeltest_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltest',
            name='activo',
            field=models.CharField(choices=[('1', 'SI'), ('0', 'NO')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='modeltest',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modeltest',
            name='identity_document',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='modeltest',
            name='typeThird',
            field=models.CharField(choices=[('employees', 'employees'), ('customers', 'customers'), ('providers', 'providers')], default='employees', max_length=100),
        ),
    ]
