# Generated by Django 4.2.9 on 2024-03-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_alter_modeltest_typethird'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltest',
            name='activo',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='modeltest',
            name='typeThird',
            field=models.CharField(max_length=100),
        ),
    ]
