# Generated by Django 4.2.9 on 2024-03-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_modeltest_activo_alter_modeltest_typethird'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeltest',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='modeltest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='modeltest',
            name='identity_document',
        ),
        migrations.RemoveField(
            model_name='modeltest',
            name='typeThird',
        ),
    ]
