# Generated by Django 4.2.9 on 2024-03-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_modeltest_typethird'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltest',
            name='activo',
            field=models.CharField(default='si', max_length=2, null=True),
        ),
    ]
