# Generated by Django 4.2.9 on 2024-03-16 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_alter_modeltest_identity_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltest',
            name='telefono',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(code='invalid', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='telefono'),
        ),
    ]
