# Generated by Django 4.2.9 on 2024-03-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_alter_modeltest_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltest',
            name='typeThird',
            field=models.CharField(blank=True, choices=[('clients', 'Clients'), ('Suppliers', 'Suppliers'), ('employees', 'Employees'), ('Financial Institutions', 'Financial Institutions')], default='employees', max_length=100, null=True),
        ),
    ]
