# Generated by Django 4.2.9 on 2024-04-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_alter_modeltest_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltest',
            name='activo',
            field=models.CharField(default='no', max_length=2),
        ),
    ]
