# Generated by Django 4.2.9 on 2024-04-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_alter_modeltest_typethird'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltest',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
