# Generated by Django 4.2.9 on 2024-05-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelThird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('identity_document', models.CharField(max_length=22)),
                ('hora', models.TimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'thirdsF',
                'db_table': 'thirdF',
            },
        ),
    ]
