# Generated by Django 4.2.9 on 2024-03-16 08:46

from django.db import migrations, models
import terceros.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelThird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[terceros.models.validate_name], verbose_name='name')),
                ('email', models.EmailField(max_length=254, validators=[terceros.models.validate_email], verbose_name='email')),
                ('phone', models.CharField(max_length=17, validators=[terceros.models.validate_phone], verbose_name='phone')),
                ('address', models.CharField(max_length=50, validators=[terceros.models.validate_address], verbose_name='address')),
                ('typeThird', models.CharField(choices=[('clients', 'Clients'), ('Suppliers', 'Suppliers'), ('employees', 'Employees'), ('Financial Institutions', 'Financial Institutions')], default='employees', max_length=100, verbose_name='typeThird')),
                ('activo', models.CharField(choices=[('1', 'SI'), ('0', 'NO')], default='1', max_length=2, verbose_name='Activo')),
                ('description', models.TextField(max_length=70, verbose_name='description')),
                ('identity_document', models.CharField(max_length=20, validators=[terceros.models.validate_identity_document], verbose_name='identity_document')),
                ('hora', models.TimeField(auto_now=True, verbose_name='Hora de registro')),
            ],
            options={
                'verbose_name': 'thirdsF',
                'db_table': 'thirdF',
            },
        ),
    ]
