# Generated by Django 4.2.9 on 2024-02-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelThird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name and lastname')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=17, verbose_name='phone')),
                ('address', models.CharField(max_length=50, verbose_name='Your Address')),
                ('typeThird', models.CharField(choices=[('clients', 'Clients'), ('Suppliers', 'Suppliers'), ('employees', 'Employees'), ('Financial Institutions', 'Financial Institutions')], default='employees', max_length=100, verbose_name='Type Third')),
                ('activo', models.CharField(choices=[('1', 'SI'), ('0', 'NO')], default='1', max_length=2, verbose_name='Activo')),
                ('description', models.TextField(verbose_name='description')),
                ('campo_new', models.CharField(max_length=7, verbose_name='campo_new')),
                ('campo_new_two', models.CharField(max_length=20, verbose_name='campo_new_two')),
                ('campo_new_three', models.CharField(max_length=30, verbose_name='campo_new_three')),
                ('campo_new_four', models.CharField(max_length=20, verbose_name='campo_new_four')),
            ],
            options={
                'verbose_name': 'thirdsF',
                'db_table': 'thirdF',
            },
        ),
    ]
