# Generated by Django 4.2.9 on 2024-02-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelthird',
            name='campo_new_four',
        ),
    ]
