# Generated by Django 4.2.9 on 2024-02-23 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0003_modelthird_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelthird',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now, null=True, verbose_name='Hora de registro'),
        ),
    ]
