# Generated by Django 4.2.9 on 2024-02-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0005_alter_modelthird_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelthird',
            name='hora',
            field=models.DateTimeField(auto_now=True, verbose_name='Hora de registro'),
        ),
    ]
