# Generated by Django 4.2.9 on 2024-02-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0007_alter_modelthird_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelthird',
            name='campo_new',
            field=models.CharField(max_length=100, verbose_name='campo_new'),
        ),
    ]
