# Generated by Django 4.2.9 on 2024-02-26 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0008_alter_modelthird_campo_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelthird',
            name='campo_new',
        ),
        migrations.RemoveField(
            model_name='modelthird',
            name='campo_new_three',
        ),
        migrations.RemoveField(
            model_name='modelthird',
            name='campo_new_two',
        ),
        migrations.AddField(
            model_name='modelthird',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='modelthird',
            name='identity_document',
            field=models.CharField(default='N/A', max_length=20, verbose_name='Identity Document'),
        ),
        migrations.AlterField(
            model_name='modelthird',
            name='description',
            field=models.TextField(max_length=100, verbose_name='description'),
        ),
    ]
