# Generated by Django 4.2.9 on 2024-02-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, unique=True)),
                ('lastname', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('genderAll', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Contacts',
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='third',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, unique=True)),
                ('lastName', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('thirdPartyType', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'thirds',
                'db_table': 'third',
            },
        ),
    ]
