# Generated by Django 4.2.9 on 2024-03-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelBoostrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('ide', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('activo', models.CharField(max_length=10)),
                ('typethird', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'modelBoostrap_app',
                'db_table': 'modelBoostrapApp',
            },
        ),
    ]
